### ISSUE TITLE
Draw Tools Paste prompt length limit in Chrome

### ISSUE THREAD

**Issue by XQlusioN** [iitc-project/ingress-intel-total-conversion#1017]
Chrome has a length limit of JS prompts of 2000 characters and ellipsizes when pasting something longer.

Could the prompt be changed to a textarea similar to copy?

**Comment by MarekKnapek** [comment]
Pasting to prompt is a non-issue, it will show ellipsis, but entire text is transferred non-damaged. I tested it with 8 MB input and it worked fine. The other way - copying text out of prompt has this limitation, you cannot display and copy text longer than 200 characters in Chrome and somewhat about 1000000 characters in Firefox.

I suggest to close this issue as invalid / wont-fix.
