### ISSUE TITLE
portalAdded hook

### ISSUE THREAD

**Issue by nfacha** [iitc-project/ingress-intel-total-conversion#1094]
Hello,
Could you provide a json exemple of the data returned by the portalAdded hook?

**Comment by nhamer** [comment]
data = { portal: portalObject, previousData: portalObject };

Both are live objects (previousData may be undefined) of the same type as window.portals[selectedPortal], they can't readily be converted into JSON. You can just directly inspect them in the debugger, though.

Hope that's helpful. It's a little less than a year in response, which is pretty good by portal approval standards :)
