### ISSUE TITLE
portalDetailLoaded hook in map_data_request does not handle data.success==false

### ISSUE THREAD

**Issue by wto605** [iitc-project/ingress-intel-total-conversion#1101]
In map_data_request there is a hook for portalDetailLoaded

```
  // add a portalDetailLoaded hook, so we can use the exteneed details to update portals on the map
  var _this = this;
  addHook('portalDetailLoaded',function(data){
    _this.render.processGameEntities([data.ent]);
  });
```

However, this hook can be called even if the detail loading did not succeed and in this case there is no data.ent.

```
  if (success) {
[snip]
    window.runHooks ('portalDetailLoaded', {guid:guid, success:success, details:dict, ent:ent});

  } else {
    if (data && data.error == "RETRY") {
      // server asked us to try again
      portalDetail.request(guid);
    } else {
      window.runHooks ('portalDetailLoaded', {guid:guid, success:success});
    }
  }
```

The map_data_request code cannot handle this and will throw a (rather common) exception when attempting to debug plugins.

**Comment by billplaysonline** [comment]
Question, Should this be restricted to portals level of zoom?

**Comment by wto605** [comment]
I'm mostly retired from ingress/IITC, but this goes back to a philosophical discussion I believe I saw elsewhere when researching the issue.

IITC natively only loads details when a portal is selected. Extension have access to portalDetail.request however, and may request bulk details (which result in bans). The discussion on whether IITC, or an (optional) middle-man extension, the requesting extension, or the user were "responsible" for avoiding ban-inducing requests.

My 2 cents: this question doesn't belong here. By definition, the detail request has already happened for this portal (that's why we're in the portalDetailLoaded hook) and re-issuing it, while server-visible, is not a *new* event. This is more about maintaining a clean console for debug when attempting to use this hook.

P.S. this hook is also usable (in theory) by extension that aren't making detail requests themselves and those developers would run into the same issue.
