### ISSUE TITLE
OSM Mapquest tiles are no longer available

### ISSUE THREAD

**Issue by pleasantone** [iitc-project/ingress-intel-total-conversion#1117]
repeat by:
Log in.
Point to someplace like San Francisco, zoom in to 13 or deeper.
Select MapQuest OSM.
See GIF where tiles are supposed to be.
Read URL in GIF.
Get upset.
Install Native OSM plugin.

fix by:
Remove MapQuest OSM and make Native OSM part of the core.

**Comment by Yossi** [comment]
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

URL for the lazy

**Comment by mxxcon** [comment]
Stock OSM is not the same as MapQuest OSM...

**Comment by pleasantone** [comment]
It's the closest that still works. Mapquest has gone paid.

**Comment by Xiretza** [comment]
Another solution might be to give users the ability to enter their own MapQuest license key. Not sure if MQ would be a big fan of that (or if they even give out free plans to non-businesses), but worth looking into.

**Comment by mxxcon** [comment]
Is 15000/month free requests means 15000 requests for image tiles? I have no idea since I never counted it, but it might be a very small amount for even a casual intel operator...?

**Comment by Xiretza** [comment]
If I understood the blog entry correctly, 1 transaction = 1 initial map load OR 1 zoom level change. Except if one tile uses one "request to the Static Map API Web Service" (whatever exactly that is), it should be way more than 1 tile/transaction.

**Comment by Cyriaqu3** [comment]
The script is not usable anymore with this "bug"

**Comment by Cojad** [comment]
From the actually MapQuest Developer Transaction log usage, I think this transaction is "session based." I have invented my own MapQuest OSM layer as map plugin which adopted the new API.
For a group of my friends to use. But transaction report is way much more less than I expected.

**Comment by flamusdiu** [comment]
@Cojad "more less" ? I don't understand your comment about the transaction report ...

**Comment by Cojad** [comment]
oops... something must hit my brain that day.
I mean much fewer than I expected.

**Comment by nemobis** [comment]
Similar to GNOME, it may be possible to fit in the MapBox free tier. https://mail.gnome.org/archives/maps-list/2016-July/msg00017.html

**Comment by HeroCC** [comment]
@Cyriaqu3, click the button that looks like 3 pieces of paper on top of each other, and change it to anything else.

**Comment by TetraEtc** [comment]
Has any work been done, or a PR opened that removes mapquest as the default map choice?

**Comment by modos189** [comment]
Reading the news about what was done in gnome, I was going to send a commit with the move to mapbox, but 82 pull requests? Seriously?

**Comment by mxxcon** [comment]
This was already addressed in e9b811036a16718993d5c5118eaf4d93e1da77e4

**Comment by Blaisorblade** [comment]
@mxxcon Not quite, even though that commit is merged. I just installed from scratch the latest stable and test builds of IITC mobile, and neither has the fix, both show MapQuest by default. That's version `0.25.2.4000.761ec2a`; haven't been able to find commit 761ec2a.

**Comment by mxxcon** [comment]
Well, yes. committed and merged, but a new release have not been cut in a while.

**Comment by dingram** [comment]
I'm looking to cut a new release after this weekend's anomalies.

**Comment by dingram** [comment]
@modos189 I know the pull requests have been mounting up. I would like to address them soon. If you want to help out, I would appreciate some testers to make sure they are safe.

**Comment by modos189** [comment]
https://github.com/iitc-project/ingress-intel-total-conversion/pull/1133

**Comment by nhamer** [comment]
This is in the stable build and should be closed.
