### ISSUE TITLE
build.py no longer functioning with python 2.x

### ISSUE THREAD

**Issue by microchip** [iitc-project/ingress-intel-total-conversion#1140]
Attempting to run "build.py local" on python 2.7.6 resulted in a failure:
Traceback (most recent call last):
  File "./build.py", line 239, in <module>
    f.write(time.strftime('%Y-%m-%d %H:%M:%S UTC', utcTime))
TypeError: must be unicode, not str

Same error didn't occur when running manually via python3.

**Comment by pleasantone** [comment]
Sounds like a feature, not a bug. :-)

**Comment by microchip** [comment]
I wouldn't report it but for the readme that says "To build the browser scripts from source you will need Python (either a late version 2.x, or 3.0+). It should build correctly on Linux and Windows (and, probably, Macs, FreeBSD, etc)" ;-)

**Comment by s-chizhik** [comment]
@microchip I've made a little workaround [here](https://github.com/s-chizhik/ingress-intel-total-conversion/commit/8d806bdc485905e15e55fea40f38b8327e9a87cd). Hope it will help you.

**Comment by dossy** [comment]
Just to add a data point, the build.py script still works fine for me with Python 2.7.11 on OSX El Capitan 10.11.6.

**Comment by dingram** [comment]
There was a fix in 0afa46a18cb796e11d92fafa0a71f8d9b65d34fb, which is why it started working again. I'm not sure I like the fix overmuch, but it's still a fix :-)
