### ISSUE TITLE
IITC doens't run anymore

### ISSUE THREAD

**Issue by damienturck** [iitc-project/ingress-intel-total-conversion#1145]
Extract from the console :
Error:
 Script returned non-structured-clonable data(source inconnue)
TypeError: L is not a constructor
[En savoir plus]gen_dashboard_12d1fb5ec5babcdea7e40f661f0a8c8068452573.js:274:256
uncaught exception: [object Event](source inconnue)
aucun élément trouvécensus:1:1
aucun élément trouvécensus:1:1
aucun élément trouvépage:1:1
Error: Script returned non-structured-clonable data(source inconnue)
![echec](https://cloud.githubusercontent.com/assets/23404048/20327435/536422dc-ab8d-11e6-9dd6-0c2e21974fc9.PNG)

**Comment by McBen** [comment]
do you have the addon "ghostly" installed?

**Comment by damienturck** [comment]
Sure i have it.

I tried to open iitc with all script abd add on desactivated : same result.

Finally, i opened ff on safe mode. Reopened it on normal mode, and then iitc is now working.

Something was Wrong between FF / greasemonkey / the scripts installed.

And maybe others add on as ghostly..

**Comment by dingram** [comment]
If you do find a way to reproduce this issue, please re-open it. Otherwise I'll mark it "closed" for now.
