### ISSUE TITLE
[Question] Understanding how iitc aquires Data in Local Storage

### ISSUE THREAD

**Issue by MTRNord** [iitc-project/ingress-intel-total-conversion#1167]
I am trying to set `ingress.intelmap.layergroupdisplayed` with the value:
```
{
"Unclaimed/Placeholder Portals":false,
"Level 1 Portals":true,"Level 2 Portals":true,
"Level 3 Portals":true,"Level 4 Portals":true,
"Level 5 Portals":true,"Level 6 Portals":true,
"Level 7 Portals":true,"Level 8 Portals":true,
"Fields":true,
"Links":true,
"Resistance":true,
"Enlightened":true,
"DEBUG Data Tiles":false,
"Artifacts":true,
"Ornaments":true,
"Player Tracker Resistance":true,
"Drawn Items":true,
"Cross Links":true
}
```
and after that I load IITC into the ingress Page. My Problem is "Unclaimed/Placeholder Portals" are still shown. But If I set fields to false they aren't shown. Am I missing something here? PS: I am using Phantomjs so reload is no Option but on PC that fixes it.

**Comment by nhamer** [comment]
I don't know where you got the "Unclaimed/Placeholder Portals" member - the value IITC reads/uses is simply "Unclaimed" (@744 in the current release), so you're just setting something it doesn't read

**Comment by MTRNord** [comment]
Ah ok. I got that from ingress-ice :) thaks for info.

**Comment by MTRNord** [comment]
That also does not hide the portals if it is set to false.

**Comment by nhamer** [comment]
"Unclaimed Portals":false

**Comment by MTRNord** [comment]
that also still shows them at zoom level 18.  I will try on desktop. maybe it is a issue with phantomjs

**Comment by MTRNord** [comment]
Ah my fresh install (nightly) says "Unclaimed/Placeholder Portals" :/ thats the generated string by iitc on first run

**Comment by MTRNord** [comment]
If i set that to false in the local storage at my desktop pc iitc hides them.

**Comment by MTRNord** [comment]
ok maybe i got initialy a problem. now it works :)

**Comment by nhamer** [comment]
This changed in commit 8f6f89a - just the first official build since then,
on Jan 8th :)
