### ISSUE TITLE
hooks.js missing documentation for runhook portalDetailsUpdated

### ISSUE THREAD

**Issue by hayeswise** [iitc-project/ingress-intel-total-conversion#1180]
The runhook `portalDetailsUpdated` is not documented in hooks.js.  This runhook is called when the portal details display is updated after you click on a portal.

```
// portalDetailsUpdated: called after the portals details display is updated.  Provides a data
//    object containing information about the displayed portal: the guid, a portal object, a  
//    portalData object, and a portalDetails object.
```

**Comment by nhamer** [comment]
You could certainly submit a pull request to update it, but it is documented:

// portalDetailsUpdated: fired after the details in the sidebar have
//              been (re-)rendered Provides data about the portal that
//              has been selected.

**Comment by hayeswise** [comment]
I searched and missed it.  Thanks.
