### ISSUE TITLE
Permalink does not include pll= when portal is selected (with solution)

### ISSUE THREAD

**Issue by awozniak** [iitc-project/ingress-intel-total-conversion#1182]
I get annoyed that Permalink does not have the pll= with the actual lat/lng of the portal.  I often need the actual lat/lng to port into something else, like google maps.

I'm too lazy to git clone and all that, but here's the fix for the problem:

window.setPermaLink = function(elm) {
  var c = map.getCenter();
  var lat = Math.round(c.lat*1E6)/1E6;
  var lng = Math.round(c.lng*1E6)/1E6;
  var qry = 'll='+lat+','+lng+'&z=' + map.getZoom();

// BEGIN ADDITIONAL CODE
  if(window.selectedPortal && window.portals[window.selectedPortal]) {
    var p = window.portals[window.selectedPortal].getLatLng();
    lat = Math.round(p.lat*1E6)/1E6;
    lng = Math.round(p.lng*1E6)/1E6;
    qry += '&pll='+lat+','+lng;
  }
// END ADDITIONAL CODE

  $(elm).attr('href',  '/intel?' + qry);
}

**Comment by awozniak** [comment]
(of course immediately after I post this I find the "Portal Link" and "Map Links". Doh!)

**Comment by PrinterElf** [comment]
Beat me to it 😂

**Comment by miron341** [comment]
pomozesz mi?
