### ISSUE TITLE
Required value 'version' is missing or invalid when installing.

### ISSUE THREAD

**Issue by crehbein** [iitc-project/ingress-intel-total-conversion#1201]
Hello.  Setting up a new desktop computer, when I try to add the extension I'm getting the above error.  Standard Chrome installation, have tampermonkey, nothing unusual about my setup.  Tried both the release and test builds and received the same error.

![image](https://cloud.githubusercontent.com/assets/9352448/24066941/251062c2-0b4d-11e7-8d0a-cd37305ca56c.png)

Platform: Win 10 - Browser: Chrome Version 56.0.2924.87

**Comment by fkloft** [comment]
This happens when Chrome is handling the userscript instead of Tampermonkey. You have to restart Chrome after installing TM.
