### ISSUE TITLE
Sync doesn't work on Chrome

### ISSUE THREAD

**Issue by RuioWolf** [iitc-project/ingress-intel-total-conversion#1214]
I tried delete it from Google Drive, and clear Cookie / Cache still doesn't work. It shows "Authorized" and do nothing any more. Works fine on Android IITC. Any idea?
![image](https://cloud.githubusercontent.com/assets/15277799/26188698/40321526-3bd3-11e7-9d29-ca26a8f519a8.png)
Besides, everytime I refresh the map position reset, and I need to select the layer again to see the map.

**Comment by JonnyTech** [comment]
Disable all browser extensions - except for IITC scripting of course.

**Comment by RuioWolf** [comment]
Works fine when only "Ingress intel map total conversion" is on.

**Comment by RuioWolf** [comment]
Hum... Problem solved, but still don't know how the problem came from. Thank you :D
