### ISSUE TITLE
IITC broken (desktop version)

### ISSUE THREAD

**Issue by SignFinder** [iitc-project/ingress-intel-total-conversion#1222]
A few days IITC doesn't work.
![default](https://user-images.githubusercontent.com/299814/28355400-7aaaa8ca-6c6c-11e7-8175-48a8373e8fc4.png)

**Comment by gusowski1** [comment]
For me it works. Could you provide further information?

**Comment by SignFinder** [comment]
Sorry for my lazy report without proper diagnostics.
IITC works fine, the problem was in other script (additional JS fix from adblock plus).
