### ISSUE TITLE
iitc.me not avaliable

### ISSUE THREAD

**Issue by ReinRaus** [iitc-project/ingress-intel-total-conversion#1224]
Change hosting user.js to github.pages, without site iitc.me

**Comment by g-t-u** [comment]
You may trying to access iitc.me from Russia.
It's being blocked here, see 
https://reestr.rublacklist.net/search/?q=104.28.13.119
https://reestr.rublacklist.net/search/?q=104.28.12.119

**Comment by ReinRaus** [comment]
Алексей, you are from Russia? My english is bad.
Несомненно, очень приятно держать иитц.ми на одном хосте с непонятным торрент-треккером, который в любой момент может быть заблокирован в любой стране, а не только в России из-за великого сериала «Молодежка».
Домен нужно привязать к github.pages и хостить сайт на github. Либо удалять торренты с хоста и подавать аппеляцию. Но текущая обстановка- стыдоба полная.

**Comment by g-t-u** [comment]
1. IP-адреса принадлежат CDN Cloudflare, так что это ничего не говорит о соседстве с упомянутым торрент-трекером.
2. Завтра заблокируют github.pages и что?

Стыдоба - это терпеть имеющийся режим цензурирования сети в России, и глупо требовать от разработчиков технического решения политической проблемы.
