### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by Suburbanno** [iitc-project/ingress-intel-total-conversion#1234]

**Comment by nhamer** [comment]
resting

**Comment by SignFinder** [comment]
Can someone fork the project and produce the release with the fixes? IITC doesn't work with new FF after 2 monthes already.

**Comment by JonnyTech** [comment]
What doesn't work? No problem here running IITC with Firefox 57.0.4 using [Violentmonkey](https://violentmonkey.github.io/get-it/) and many IITC plugins. Can you be more specific?

**Comment by SignFinder** [comment]
Sure, I can. Not me directly.
https://github.com/iitc-project/ingress-intel-total-conversion/pull/1249

**Comment by JonnyTech** [comment]
Ah, they are using Greasemonkey. As I said, I use Violentmonkey. It works flawlessly for me.

What exactly is not working? Please provide specific examples with details.

**Comment by SignFinder** [comment]
@JonnyTech 
Greasemonkey 4.0 changed the API which is used by the script. This change is backwards incompatible as written in the announcement: https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html

So, every script using one of these functions needs to adapt to this new API to continue working. As long as a script is not adapted, it will not work.

**Comment by JohnCalin** [comment]
I've resolved this in my own system.  Not sure the best way to suggest the updated code here, so I'll just post it.

Change this:
`if (typeof(window.PLAYER)!="object" || typeof(window.PLAYER.nickname) != "string") {`

To this:
`if (typeof(unsafeWindow.PLAYER)!="object" || typeof(unsafeWindow.PLAYER.nickname) != "string") {`

I hope this helps.
