### ISSUE TITLE
Desktop IITC doesn't work with Firefox 57 (Quantum) and Greasemonkey 4

### ISSUE THREAD

**Issue by SignFinder** [iitc-project/ingress-intel-total-conversion#1251]
Hi folks,
Desktop IITC doesn't work with Firefox 57 (Quantum) and Greasemonkey 4
Authors of Greasemonkey showed me this documents
http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

**Comment by McBen** [comment]
https://github.com/iitc-project/ingress-intel-total-conversion/pull/1249

**Comment by SignFinder** [comment]
Thanks. I hope the changes were published in a few time.
