### ISSUE TITLE
Missions in View incomplete

### ISSUE THREAD

**Issue by Micromegas2016** [iitc-project/ingress-intel-total-conversion#1252]
Currently, Missions in View does not display all missions. This is because missions.user.js relies on the function `getTopMissionsInBounds`, which only presents a selection. (Apparently by how they are voted.) 

This is a problem not only for finding missions that one might like to do (for which ingressmosaik.com provides an excellent workaround), but also for applying IITC's neat feature to mark portals of completed missions as visited. Example: In https://www.ingress.com/intel?ll=50.143,8.504&z=17, the mission "Bad Soden round tour", does not show regardless of the zoom setting. 

I therefore suggest using a function other than `getTopMissionsInBounds`, if one exists. Ideally, an unfiltered one. If that significantly increases server load, then I would suggest using a different filtering criterion, such as proximity of first portal to center of view. 

If no other function than `getTopMissionsInBounds` exists, then I suggest using the information from ingressmosaik.com instead. 

Since, as in the above example, it is often the case that single missions are crowded out by mosaic missions, it would be helpful to distinguish between the two. Mosaic missions could be shown in its entirety, with functionality as if they were a single mission, e.g. allowing the user to mark all portals of a mosaic at once. 

To distinguish the two, there are several options:

1. Simple heuristic by name: e.g. with a regular expression like `(\(\d+\))|( \d+$)`.
2. Comparison with other mission names to find common patterns. 
3. Getting that information from ingressmosaik.com.

**Comment by nhamer** [comment]
(a) no such alternate API exists, (b) that would be a good feature request for the ingressmosaik plugin

**Comment by Micromegas2016** [comment]
Good suggestion; I wasn't even aware of that plugin. This closes the issue for me. 

I hope to get around to that in the next month or two. For future reference: See [Announcement of Oct 28](https://plus.google.com/+OhneNotEnlightened/posts/gEx7RNTydgF) and [Announcement of Nov 1](https://plus.google.com/+OhneNotEnlightened/posts/F1t18X6UTjb).
