### ISSUE TITLE
Sync problems in Firefox or Chrome and third party cookies

### ISSUE THREAD

**Issue by Eccenux** [iitc-project/ingress-intel-total-conversion#1269]
So this is only for reference as I actually just solved this. Sometimes `sync` might not work for you in one browser but will work for others.

The problem
--------------

You might get one of two errors in "Sync" window:

* "Authorization error: localStorage is not available in the current environment."
* "Authorization error: idpiframe_initialization_failed"

If you are not getting any errors but sync is still not working then do this:

1. Open "Sync" window.
2. Open developer tools (CTRL+SHITF+I should work).
3. Paste in the console this command (and press enter): `window.plugin.sync.authorizer.authorize()`

If authorization is working you should get `PM: Authorized`. Otherwise you should see some error message.

The solution
----------------
Turns out this is a cookie problem (contrary to the messages).

### Firefox ###

1. Go to Preferences -> Privacy (or url: about:preferences#privacy).
2. In Cookies you should see "Accept cookies and site data from websites (recommended)" option.
3. Change "Accept third-party cookies and site data" sub-option to "Always".

### Chrome ###

See [this answer on stacoverflow](https://stackoverflow.com/a/42806178).

**Comment by fkloft** [comment]
Was also a problem with allowed origins due to Intel URL change. Fixed.
