### ISSUE TITLE
Niantic changed the URI of Intel

### ISSUE THREAD

**Issue by feeshy** [iitc-project/ingress-intel-total-conversion#1276]
The URI of intel is changed from `ingress.com/intel` to `intel.ingress.com/intel`. And on the mobile version of IITC, the webpage does not automatically jump back to IITCm after you have logged-in on the browser.

**Comment by terencehonles** [comment]
This is fixed with #1277, but we'll need someone to sign the APK

**Comment by alcr** [comment]
New URL is `intel.ingress.com` /intel is optional and can be discarded

**Comment by johnd0e** [comment]
Could anyone upload updated apk somewere?

**Comment by Jomiryo** [comment]
Someone uploaded it :) http://ru.ietoday.net/f/IITC_Mobile.apk

**Comment by ExtremeMoves** [comment]
http://ru.ietoday.net/f/IITC_Mobile.apk
The file does not work posted above.

**Comment by Holguitar** [comment]
Works for me. Uninstall further version, Allow unknown sources.

**Comment by ExtremeMoves** [comment]
I uninstalled the old version and installed the posted file and it came up with wanting to open the intel in a separate browser so i dont believe the file is legit.

**Comment by mangofire263** [comment]
I loaded it, but niantic shut the door, it worked for 10 minutes

**Comment by Jo0Lz** [comment]
> I loaded it, but niantic shut the door, it worked for 10 minutes

The intel site was down a while, it's working again now.

**Comment by drh4kor** [comment]
I prefer the official APK but I need this!! For now the APK works.

**Comment by drh4kor** [comment]
Niantic is using the new Google login for better Google standards in OAuth sec.

**Comment by lucifer6642** [comment]
> http://ru.ietoday.net/f/IITC_Mobile.apk
Virustotal shows a potential issue in com.cradle.iitc_mobile for that APK and two people I know that tried it out say it wasn't working.

**Comment by ka11n** [comment]
У меня прекрасно все работает!

**Comment by Holguitar** [comment]
> 
> 
> > http://ru.ietoday.net/f/IITC_Mobile.apk
> > Virustotal shows a potential issue in com.cradle.iitc_mobile for that APK and two people I know that tried it out say it wasn't working. I'd wait for an official release.

Are you serious? 1 out of 59? https://www.virustotal.com/de/file/0cfb7773b62d0b221af021b2df15ee38287010becd49a722d4f447f94d42ba05/analysis/ That could be the result of every random file you check. It´s your choice to wait for an offical release but don´t scare  the people.

**Comment by lucifer6642** [comment]
1/59 could indeed be a false positive. However, I did decompile it and start doing comparisons. Sure I saw some edits that weren't purely those required so I'd like to know what branch it was from before declaring it safe. And I did mention some friends trying it out and it didn't work.
