### ISSUE TITLE
draw-tools on mobile: unable to draw circle

### ISSUE THREAD

**Issue by johnd0e** [iitc-project/ingress-intel-total-conversion#1294]
We can live without it, so (until fixed) it is better to remove icon from toolbar in order to save some place (it's important on small mobile screen).

It would be even better if we could customize draw panel defining which icons to hide.

**Comment by Eccenux** [comment]
There is no reason why circles couldn't work for mobile. In fact there are editors which allow to do vector graphics on mobile browsers... Just probably need some tweaking...

Having said that personally I don't draw circles on IITC, so I'm all for personalization.

**Comment by johnd0e** [comment]
> There is no reason why circles couldn't work for mobile.

https://leaflet.github.io/Leaflet.draw/docs/examples/full.html
And circle works here.

> so I'm all for personalization.

Well, it can be done via css, by some plugin.
