### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by AzureIP** [iitc-project/ingress-intel-total-conversion#1306]
Hi,
I think about developing some route planning tool for location based games. For example for Ingress. At a first step I want to try out the browser plugin IITC. Maybe my Idea could become a plugin.
But after I installed Greasmonkey on Firefox and hit the download button on https://iitc.me/desktop/ the intel site isn't working anymore. It looks like the old one but doesn't loads a map.

**Comment by andrewfhou** [comment]
Try changing the map later to the Default Ingress Google Map, I've had an issue where the default map for IITC doesn't load for me

**Comment by johnd0e** [comment]
https://intel.ingress.com/intel

**Comment by AzureIP** [comment]
Yes, exactly that site. If I click on the link I come to a site that looks like the old site but does not load anything. I don't thnk I can change there any settings. If I deactivate the script it is working again. (The standrd version.)

**Comment by AzureIP** [comment]
Ah, got it. Simply leave this site and continue here: https://github.com/IITC-CE/ingress-intel-total-conversion

**Comment by andrewfhou** [comment]
You may have to edit the script to include the intel.ingress.com url, I don't know what version you have

**Comment by AzureIP** [comment]
The one from https://iitc.me/desktop/.
