### ISSUE TITLE
plugin idea: OpenGTS plugin

### ISSUE THREAD

**Issue by ZyanKLee** [iitc-project/ingress-intel-total-conversion#180]
create new plugin which adds marker for player positions gathered from an opengts (http://www.opengts.org/) server.
- User needs to add own authentication data for the server
- User needs to add url for opengts server of his/her group
  (both saved to a cookie and read from it at next browser start?)
- Marker are shown similar to the player tracker plugin: opponent team is shown from ingress intel data only, but own team from opengts data as well

**Comment by nhamer** [comment]
Suggestion not implemented in 3+ years, can issue be closed?

**Comment by ZyanKLee** [comment]
@nhamer most likely, yes. I don't think this will be needed by anyone after that long time.

**Comment by johnd0e** [comment]
Just want to note some alternatives:
- Glympse
- OwnTracks
