### ISSUE TITLE
Escape portal's address in Chat links

### ISSUE THREAD

**Issue by user890104** [iitc-project/ingress-intel-total-conversion#829]
Currently, any portal link in chat that contain a quotation mark in the street address (e.g. 34 "Main" Street) is broken. Title is truncated to the first quotation mark, and the rest are parsed as HTML attributes.
Fix:
in function chat.writeDataToHash, replace:

    msg += '<a onclick="'+js+'"'
          + ' title="'+markup[1].address+'"'
          + ' href="'+perma+'" class="help">'
          + window.chat.getChatPortalName(markup[1])
          + '</a>';

with:

    var el = document.createElement('span');
        el.textContent = markup[1].address;
        
        msg += '<a onclick="'+js+'"'
          + ' title="'+el.innerHTML.replace(/"/g, '&quot;')+'"'
          + ' href="'+perma+'" class="help">'
          + window.chat.getChatPortalName(markup[1])
          + '</a>';

It should also escape other HTML special characters (less-than, greater-than, etc.)
Tested on Firefox 30 (GM)

**Comment by MarekKnapek** [comment]
Created pull request: https://github.com/jonatkins/ingress-intel-total-conversion/pull/1063
