### ISSUE TITLE
Software back button for mobile info page

### ISSUE THREAD

**Issue by pleasantone** [iitc-project/ingress-intel-total-conversion#904]
This is a feature request. Some of us are using iitc in a mobile Safari bookmarklet with iOS.
Could we please get a back button on the portal information page? It's ok if it's a plugin, but it's sorely necessary as there is no way to return to the map otherwise since we don't have a hardware back button.

**Comment by dossy** [comment]
Adding a globally accessible software "back" button to IITC on mobile Safari might be really difficult, but I threw together a quick plugin for my own use to add a  "Show Map" button to the toolbox to make it possible to dismiss the info screen, which is like 99% of why I personally would want a "back" button.

[toolbox-show-map-button.user.js](https://github.com/dossy/ingress-intel-total-conversion/blob/plugin-toolbox-show-map-button/plugins/toolbox-show-map-button.user.js)

**Comment by dossy** [comment]
I'm also throwing a copy up (here's the [gist](https://gist.github.com/dossy/37018a19099f0174f3bd1220fd7f3354)) so folks can test and try this out:

https://git.io/vimBB
