### ISSUE TITLE
TypeError: window.plugin.bookmarks.bkmrksObj.portals is undefined

### ISSUE THREAD

**Issue by AndOne1974** [iitc-project/ingress-intel-total-conversion#965]
TypeError: window.plugin.bookmarks.bkmrksObj.portals is undefined
	

intel?l....529874 (Zeile 354, Spalte 4)

latest test build, latest test build bookmarks plugin

just try to bookmark a loaded portal, in my case this portal: https://www.ingress.com/intel?ll=48.449179,-68.531822&z=16&pll=48.450162,-68.529874

**Comment by michaeldever** [comment]
This doesn't seem to be happening anymore, I can't cause it on mine anyway. Are you still having this issue?

**Comment by michaeldever** [comment]
@jonatkins I think this can be closed, doesn't seem to be happening.
