### ISSUE TITLE
Bookmarks utility functions

### ISSUE THREAD

**Issue by reckter** [iitc-project/ingress-intel-total-conversion#980]
I just looked into adding a Folder in the bookmarks plugin, automatically (via a different plugin). I couldn't find another way than using Jquery to enter the name and press the button of the input field.
Which is really hacky. So I ask for a function in the Bookmarks Folder:
'addFolder("name")'

If this is considered a good addition, I could add it myself ( doesn't look like much work really)

edit: this should also apply to maps

**Comment by flamusdiu** [comment]
@reckter If you can, might as well create the patch and submit it then @jonatkins can consider it. It would greatly help out if you do the patch for this if you can.

**Comment by flamusdiu** [comment]
If nothing else, you can create a completely separate plugin that adds the feature to that any plugin could use.

**Comment by reckter** [comment]
@flamusdiu I wanted to see if this was needed / wanted for first :) I will do it when I find some time for it.

**Comment by flamusdiu** [comment]
@reckter Yeah, i understand it; still, if you think it's worth it for yourself, then put the change up and let the masses consider it. =) Also, make it faster to pull in if it gets accepted.

**Comment by reckter** [comment]
Finally came around to implementing this. 
See #994 for more information, I added a bunch of functions, that seemed helpful for me.

**Comment by reckter** [comment]
*bump*
